### ISSUE TITLE
Decidir os papéis do scrum/xp

### ISSUE THREAD

**Issue by lucasqueiroz23** [mdsreq-fga-unb/2024.1-Nimbus#17]
- quem é o sm? 
    - quem é o po?
    - quando serão as dailies (horário)?
    - quando serão review e retrospective? esses rituais devem ser feitos no mesmo momento ou em dias diferentes?
    - quando será a planning?

**Comment by DaniloNavesS** [comment]
Lucas

**Comment by DaniloNavesS** [comment]
1. Lucas Queiroz
2. Philipe
3. A noite, a partir das 20:00h
4. Na minha visão sim
5. A noite, a partir das 20:00h

**Comment by thegm445** [comment]
1. Gabriel Moura
2. Philipe
3. A noite, a partir das 20h
4. Momentos separados
5. Nas dailies de segundas feiras
